src/main/java/jp/co/shoji/dto/CommentDto.java
package jp.co.shoji.dto;

import java.util.Date;

public class CommentDto {
    private int id;
    private String text;
    private Date created_date;
    private int message_id;
    private int is_deleted;


    public int getId() {
    	return id;
    }
    public void setId(int id) {
    	this.id = id;
    }

    public String getText() {
    	return text;
    }
    public void setText(String text) {
    	this.text = text;
    }

    public Date getCreatedDate() {
    	return created_date;
    }
    public void setCreatedDate(Date created_date) {
    	this.created_date = created_date;
    }

    public int getMessageId() {
    	return message_id;
    }
    public void setMessageId(int message_id) {
    	this.message_id = message_id;
    }

    public int getIsDeleted() {
    	return is_deleted;
    }
    public void setIsDeleted(int is_deleted) {
    	this.is_deleted = is_deleted;
    }
}

src/main/java/jp/co/shoji/entity/Message.java
package jp.co.shoji.entity;

import java.util.Date;

public class Message {
    private int id;
    private String text;
    private Date created_date;
    private int is_deleted;
    private Date updated_date;


    public int getId() {
    	return id;
    }
    public void setId(int id) {
    	this.id = id;
    }

    public String getText() {
    	return text;
    }
    public void setText(String text) {
    	this.text = text;
    }

    public Date getCreatedDate() {
    	return created_date;
    }
    public void setCreatedDate(Date created_date) {
    	this.created_date = created_date;
    }

    public int getIsDeleted() {
    	return is_deleted;
    }
    public void setIsDeleted(int is_deleted) {
    	this.is_deleted = is_deleted;
    }

    public Date getUpdatedDate() {
    	return updated_date;
    }
    public void setUpdatedDate(Date updated_date) {
    	this.updated_date = updated_date;
    }
}

src/main/java/jp/co/shoji/form/MessageForm.java
package jp.co.shoji.form;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

public class MessageForm {

	private int id;
	@NotBlank(message = "文字を入力してください")
	@Size(message = "140字以内で入力してください", max = 140)
	private String text;

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}
}

src/main/java/jp/co/shoji/controller/MessageController.java
package jp.co.shoji.controller;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.shoji.form.MessageForm;
import jp.co.shoji.service.MessageService;
@Controller
public class MessageController {

	@Autowired
    private MessageService messageService;

	@RequestMapping(value = "/message", method = RequestMethod.GET)
	public String message(Model model) {
	    MessageForm form = new MessageForm();
	    model.addAttribute("messageForm", form);
	    model.addAttribute("aMessage", "新規投稿");
	    return "message";
	}

    @RequestMapping(value = "/message", method = RequestMethod.POST)
    public String message(@Valid @ModelAttribute MessageForm form, BindingResult result, Model model) {
    	if(result.hasErrors()) {
            return "message";
    	} else {
	    	messageService.insertMessage(form.getText());
	        return "redirect:/top";
    	}
    }
}

src/main/java/jp/co/shoji/controller/TopController.java
package jp.co.shoji.controller;

import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.shoji.dto.CommentDto;
import jp.co.shoji.dto.MessageDto;
import jp.co.shoji.form.CommentForm;
import jp.co.shoji.form.DeleteCommentForm;
import jp.co.shoji.form.DeleteMessageForm;
import jp.co.shoji.service.TopService;


@Controller
public class TopController {
	@Autowired
	private TopService topService;

	@RequestMapping(value = "/top", method = RequestMethod.GET)
	public String top(Model model) {
		List<MessageDto> tempMessages = topService.getMessageAll();
		List<CommentDto> comments = topService.getCommentAll();
		List<MessageDto> messages = getMessages(tempMessages);
		model.addAttribute("aMessage", "20ch");
		model.addAttribute("messages", messages);
		model.addAttribute("comments", comments);
		return "top";
	}

	@RequestMapping(value = "/top", params = "comment", method = RequestMethod.POST)
	public String comment(@Valid @ModelAttribute CommentForm form, BindingResult result, Model model) {
		if (result.hasErrors()) {
			List<MessageDto> messages = topService.getMessageAll();
			List<CommentDto> comments = topService.getCommentAll();
			model.addAttribute("aMessage", "20ch");
			model.addAttribute("messages", messages);
			model.addAttribute("comments", comments);
			model.addAttribute("title", "エラー");
			// model.addAttribute("message", "以下のエラーを解消してください");
			return "top";
		} else {
			topService.insertComment(form);
			model.addAttribute("commentForm", form);
			return "redirect:/top";
		}
	}

	@RequestMapping(value = "/top", params = "deleteMessage", method = RequestMethod.POST)
	public String deleteMessage(@ModelAttribute DeleteMessageForm form, Model model) {
		topService.deleteMessage(form.getId());
		return "redirect:/top";
	}

	@RequestMapping(value = "/top", params = "deleteComment", method = RequestMethod.POST)
	public String deleteComment(@ModelAttribute DeleteCommentForm form, Model model) {
		topService.deleteComment(form.getId());
		return "redirect:/top";
	}

	private List<MessageDto> getMessages(List<MessageDto> list) {
		for(int i = 0; i < list.size() - 1; i++) {
			for(int j = 0; j < list.size() - 1; j++) {
				MessageDto dto1 = new MessageDto();
				MessageDto dto2 = new MessageDto();
				BeanUtils.copyProperties(list.get(j), dto1);
				BeanUtils.copyProperties(list.get(j + 1), dto2);
				if(dto1.getUpdatedDate().before(dto2.getUpdatedDate()) ) {
				    list.set(j, dto2);
				    list.set(j + 1, dto1);
				}/* else {
					list.set(j, dto1);
					list.set(j + 1, dto2);
				}*/
			}
		}
		return list;
	}
}

src/main/webapp/WEB-INF/view/message.jsp
<!DOCTYPE html>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<html>
    <head>
        <meta charset="utf-8">
        <title>Welcome</title>
        <script type="text/javascript">
		    function checkMessage(){
			    var message = document.getElementById('messageText').value;
			    if(message.length > 140){
			        window.alert('140字以下で文字を入力してください');
			        return false;
			    }
			    if(!message || !message.match(/\S/g)){
			    	window.alert('文字を入力してください');
			        return false;
			    }
			    return true;
			}
		</script>
    </head>
    <body>
        <div class="header">
            <ul>
                 <li><a href="top">トップページ</a></li>
            </ul>
        </div>
        <h1>${aMessage}</h1>
        <h2><c:out value="${title}"></c:out></h2>
        <h2><c:out value="${message}"></c:out></h2>
        <form:form modelAttribute="messageForm">
            <div><form:errors path="*" /></div>
            <textarea name="text" id="messageText" cols="60" rows="5" class="text-box"></textarea>
            <input type="submit" value="投稿" onclick="return checkMessage()">
        </form:form>
    </body>
</html>

src/main/webapp/WEB-INF/view/top.jsp
<!DOCTYPE html>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<html>
    <head>
        <meta charset="utf-8">
        <title>20ch</title>
        <link rel="stylesheet" type="text/css" href="style.css">

		<script type="text/javascript">
		    function checkComment(num){
			    var comment = document.commentForm[num].text.value;
			    // 140文文字以下判定
			    if(comment.length > 140){
			        window.alert('140字以下で文字を入力してください');
			        return false;
			    }
			    // 空文字判定
			    else if(!comment || !comment.match(/\S/g)){
			    	window.alert('文字を入力してください');
			        return false;
			    }
			    return true;
			}
			function checkDelete(){
				// 入力ダイアログを表示 ＋ 入力内容を password に代入
				const password = window.prompt("管理者パスワードを入力してください", "");
					//
				if(password == 'admini'){
					// 削除処理
					window.alert('削除しました');
					return true;
				}
				// 入力内容が一致しない場合は警告ダイアログを表示
				else if(password != "" && password != null){
					window.alert('管理者パスワードが間違っています');
					return false;
				}
				// 空の場合やキャンセルした場合は警告ダイアログを表示
				else{
					window.alert('キャンセルされました');
					return false;
				}
			}
		</script>
    </head>
    <body>
        <div class="header">
            <ul>
                <li><a href="message">新規投稿</a></li>
            </ul>
        </div>
        <h1>${aMessage}</h1>
        <form:form modelAttribute="commentForm">
            <div><form:errors path="*" /></div><br />
        </form:form>
        <c:forEach items="${messages}" var="message" varStatus="status">
            <c:if test="${message.isDeleted == 0}">
	            <h2><pre><c:out value="${message.text}"></c:out></pre></h2>
	            <form:form modelAttribute="deleteMessageForm">
	                <input type="hidden" value="${message.id}" name="id" >
	                <input type="submit" value="削除" name="deleteMessage" onclick="return checkDelete()"><br />
	            </form:form>
	        </c:if>
	        <c:if test="${message.isDeleted == 1}">
	            <h4>この投稿は削除されました</h4>
	        </c:if>
            <c:forEach items="${comments}" var="comment">
	            <c:if test="${comment.messageId == message.id}">
	                <c:if test="${comment.isDeleted == 0}">
		                <h4><pre><c:out value="${comment.text}"></c:out></pre></h4>
		                <form:form modelAttribute="deleteCommentForm">
		                    <input type="hidden" value="${comment.id}" name="id" >
		                    <input type="submit" value="削除" name="deleteComment" onclick="return checkDelete()"><br />
		                </form:form>
		            </c:if>
		            <c:if test="${comment.isDeleted == 1}">
		                <h4>このコメントは削除されました</h4>
		            </c:if>
	            </c:if>
            </c:forEach>
            <form:form modelAttribute="commentForm" name="commentForm">
	            <textarea name="text" id="commentText" cols="60" rows="5" class="text-box"></textarea>
	            <input type="submit" value="コメント" name="comment" onclick="return checkComment(${status.index})">
	            <input type="hidden" value="${message.id}" name="messageId">
	        </form:form>
        </c:forEach>
    </body>
</html>